### ISSUE TITLE
Quick Look extension

### ISSUE THREAD

**Issue by vogler** [SamusAranX/MinimalMIDIPlayer#15]
A quick look extension as here would be nice: https://github.com/benwiggy/APPlayMIDI?tab=readme-ov-file#quick-look

**Comment by SamusAranX** [comment]
I've made several attempts at getting a QL preview extension up and running in the past, but I scrapped all of them because QL just isn't made for previewing anything that's not 1. an image 2. an audio/video file already supported by QuickTime Player 3. HTML. I'll consider it if the API ever improves.

**Comment by vogler** [comment]
https://github.com/benwiggy/APPlayMIDI/tree/master/qlMIDI
Can't you just do the same? The Quick Look extension doesn't depend on the rest. It's using `AVMIDIPlayer` and has a customizable `PreviewViewController`.
