### ISSUE TITLE
similar program for Windows?

### ISSUE THREAD

**Issue by TheUser1992** [SamusAranX/MinimalMIDIPlayer#6]
Is there such a program for Windows? Through Google search I can’t find one fucking way on Windows to play .mid automatically together with .sf2. Thanks.. -_-

**Comment by SamusAranX** [comment]
Sure!

I modeled this app's behavior off that of [foobar2000](https://www.foobar2000.org/)'s [foo_midi plugin](https://www.foobar2000.org/components/view/foo_midi).
Just like this app it'll auto-select soundfonts with the same name as an opened MIDI file or the containing directory. You can also use your own soundfonts, but the process of selecting one of those is slightly more involved because it's buried in foobar's preferences window.

**Comment by TheUser1992** [comment]
Thanks! ^.^

Now I have to find out how to remove the reverberation from playback.
